### ISSUE TITLE
OpenCart stopped working

### ISSUE THREAD

**Issue by slavino** [messor-network/messor-opencart#4]
[22-Jan-2023 11:48:18] WARNING: [pool www] child 1931199 said into stderr: "Stack trace:"
[22-Jan-2023 11:48:18] WARNING: [pool www] child 1931199 said into stderr: "#0 /data/web/mydomain.com/web/system/library/messor/src/Crypt/CryptOpenSSL.php(30): openssl_random_pseudo_bytes()"
[22-Jan-2023 11:48:18] WARNING: [pool www] child 1931199 said into stderr: "#1 /data/web/mydomain.com/web/system/library/messor/src/Request/Request.php(75): src\Crypt\CryptOpenSSL->Encrypt()"
[22-Jan-2023 11:48:18] WARNING: [pool www] child 1931199 said into stderr: "#2 /data/web/mydomain.com/web/system/library/messor/src/Request/toServer.php(59): src\Request\Request->formatForSend()"
[22-Jan-2023 11:48:18] WARNING: [pool www] child 1931199 said into stderr: "#3 /data/web/mydomain.com/web/system/library/messor/src/Request/Client/Server.php(71): src\Request\toServer->status()"
[22-Jan-2023 11:48:18] WARNING: [pool www] child 1931199 said into stderr: "#4 /data/web/mydomain.com/web/system/library/messor/src/Request/Client/Client.php(55): src\Request\Client\Server->checkServerStatus()"
[22-Jan-2023 11:48:18] WARNING: [pool www] child 1931199 said into stderr: "#5 /data/web/mydomain.com/web/system/library/messor/src/Request/Client/Client.php(77): src\Request\Client\Client::start()"
[22-Jan-2023 11:48:18] WARNING: [pool www] child 1931199 said into stderr: "#6 /data/web/mydomain.com/web/system/library/messor/main/MessorLib.php(840): src\Request\Clien..."
[22-Jan-2023 11:48:36] WARNING: [pool www] child 1929296 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Length must be greater than 0 in /data/web/mydomain.com/web/system/library/messor/src/Crypt/CryptOpenSSL.php:30"
[22-Jan-2023 11:48:36] WARNING: [pool www] child 1929296 said into stderr: "Stack trace:"
[22-Jan-2023 11:48:36] WARNING: [pool www] child 1929296 said into stderr: "#0 /data/web/mydomain.com/web/system/library/messor/src/Crypt/CryptOpenSSL.php(30): openssl_random_pseudo_bytes()"
[22-Jan-2023 11:48:36] WARNING: [pool www] child 1929296 said into stderr: "#1 /data/web/mydomain.com/web/system/library/messor/src/Request/Request.php(75): src\Crypt\CryptOpenSSL->Encrypt()"
[22-Jan-2023 11:48:36] WARNING: [pool www] child 1929296 said into stderr: "#2 /data/web/mydomain.com/web/system/library/messor/src/Request/toServer.php(59): src\Request\Request->formatForSend()"
[22-Jan-2023 11:48:36] WARNING: [pool www] child 1929296 said into stderr: "#3 /data/web/mydomain.com/web/system/library/messor/src/Request/Client/Server.php(71): src\Request\toServer->status()"
[22-Jan-2023 11:48:36] WARNING: [pool www] child 1929296 said into stderr: "#4 /data/web/mydomain.com/web/system/library/messor/src/Request/Client/Client.php(55): src\Request\Client\Server->checkServerStatus()"
[22-Jan-2023 11:48:36] WARNING: [pool www] child 1929296 said into stderr: "#5 /data/web/mydomain.com/web/system/library/messor/src/Request/Client/Client.php(77): src\Request\Client\Client::start()"
[22-Jan-2023 11:48:36] WARNING: [pool www] child 1929296 said into stderr: "#6 /data/web/mydomain.com/web/system/library/messor/main/MessorLib.php(840): src\Request\Clien..."

**Comment by wwood-dev** [comment]
We are updating the server soon everything will work

**Comment by wwood-dev** [comment]
Thank you for noticing and creating the issue now all servers are working
